# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QDateTimeEdit,
    QHeaderView, QLabel, QLineEdit, QListView,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStackedWidget, QStatusBar, QTableView,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(920, 650)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 10, 1001, 624))
        self.borrowPage = QWidget()
        self.borrowPage.setObjectName(u"borrowPage")
        self.ptypeselect = QComboBox(self.borrowPage)
        self.ptypeselect.setObjectName(u"ptypeselect")
        self.ptypeselect.setGeometry(QRect(350, 100, 181, 41))
        self.pidselect = QComboBox(self.borrowPage)
        self.pidselect.setObjectName(u"pidselect")
        self.pidselect.setGeometry(QRect(350, 180, 181, 41))
        self.label = QLabel(self.borrowPage)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(240, 110, 58, 18))
        font = QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label_2 = QLabel(self.borrowPage)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(240, 190, 58, 18))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.borrowPage)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(240, 270, 58, 18))
        self.label_3.setFont(font)
        self.userselect = QComboBox(self.borrowPage)
        self.userselect.setObjectName(u"userselect")
        self.userselect.setGeometry(QRect(350, 260, 181, 41))
        self.saveborrow = QPushButton(self.borrowPage)
        self.saveborrow.setObjectName(u"saveborrow")
        self.saveborrow.setGeometry(QRect(590, 480, 91, 31))
        self.saveborrow.setFont(font)
        self.label_13 = QLabel(self.borrowPage)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(230, 360, 81, 20))
        self.label_13.setFont(font)
        self.label_14 = QLabel(self.borrowPage)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(230, 440, 81, 18))
        self.label_14.setFont(font)
        self.dateEdit_2 = QDateEdit(self.borrowPage)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.dateEdit_2.setGeometry(QRect(350, 350, 181, 41))
        self.dateEdit_3 = QDateEdit(self.borrowPage)
        self.dateEdit_3.setObjectName(u"dateEdit_3")
        self.dateEdit_3.setGeometry(QRect(350, 440, 181, 41))
        self.stackedWidget.addWidget(self.borrowPage)
        self.userPage = QWidget()
        self.userPage.setObjectName(u"userPage")
        self.label_7 = QLabel(self.userPage)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(450, 170, 58, 18))
        self.lineEdit = QLineEdit(self.userPage)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(510, 170, 113, 26))
        self.pushButton_2 = QPushButton(self.userPage)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(540, 230, 80, 26))
        self.listView = QListView(self.userPage)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(90, 80, 281, 411))
        self.label_8 = QLabel(self.userPage)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 40, 58, 18))
        self.stackedWidget.addWidget(self.userPage)
        self.recordPage = QWidget()
        self.recordPage.setObjectName(u"recordPage")
        self.label_4 = QLabel(self.recordPage)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 80, 58, 18))
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.recordPage)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(270, 80, 58, 18))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.recordPage)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(470, 80, 58, 18))
        self.label_6.setFont(font)
        self.dateEdit = QDateEdit(self.recordPage)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(110, 70, 131, 41))
        self.dateEdit.setFont(font)
        self.dateEdit.setCurrentSection(QDateTimeEdit.YearSection)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setDate(QDate(2023, 8, 1))
        self.comboBox = QComboBox(self.recordPage)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(330, 70, 121, 41))
        self.comboBox.setFont(font)
        self.comboBox_2 = QComboBox(self.recordPage)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(540, 70, 131, 41))
        self.comboBox_2.setFont(font)
        self.pushButton = QPushButton(self.recordPage)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(710, 70, 91, 41))
        self.pushButton.setFont(font)
        self.tableView = QTableView(self.recordPage)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(20, 130, 861, 461))
        self.stackedWidget.addWidget(self.recordPage)
        self.produpage = QWidget()
        self.produpage.setObjectName(u"produpage")
        self.listView_2 = QListView(self.produpage)
        self.listView_2.setObjectName(u"listView_2")
        self.listView_2.setGeometry(QRect(70, 50, 281, 531))
        self.label_9 = QLabel(self.produpage)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 20, 58, 18))
        self.label_10 = QLabel(self.produpage)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(480, 160, 58, 18))
        self.label_11 = QLabel(self.produpage)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(480, 210, 58, 18))
        self.label_12 = QLabel(self.produpage)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(480, 100, 58, 18))
        self.pushButton_3 = QPushButton(self.produpage)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(640, 290, 91, 31))
        self.lineEdit_2 = QLineEdit(self.produpage)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(560, 90, 161, 31))
        self.lineEdit_3 = QLineEdit(self.produpage)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(560, 150, 161, 31))
        self.lineEdit_4 = QLineEdit(self.produpage)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(560, 210, 161, 31))
        self.stackedWidget.addWidget(self.produpage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 920, 24))
        self.borrowMenu = QMenu(self.menubar)
        self.borrowMenu.setObjectName(u"borrowMenu")
        self.recordMenu = QMenu(self.menubar)
        self.recordMenu.setObjectName(u"recordMenu")
        self.userMenu = QMenu(self.menubar)
        self.userMenu.setObjectName(u"userMenu")
        self.productMenu = QMenu(self.menubar)
        self.productMenu.setObjectName(u"productMenu")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.borrowMenu.menuAction())
        self.menubar.addAction(self.recordMenu.menuAction())
        self.menubar.addAction(self.userMenu.menuAction())
        self.menubar.addAction(self.productMenu.menuAction())

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u53f0\u8d26\u5c0f\u5de5\u5177", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u4eea\u5668", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u7f16\u53f7", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u4eba\u5458", None))
        self.saveborrow.setText(QCoreApplication.translate("MainWindow", u"\u767b\u8bb0", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u65e5\u671f", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u675f\u65e5\u671f", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u540d\u5b57", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u589e", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u4eba\u5458\u5217\u8868", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u671f", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u4eba\u5458", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u4eea\u5668", None))
        self.dateEdit.setDisplayFormat(QCoreApplication.translate("MainWindow", u"yyyy-MM-dd", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u4eea\u5668\u5217\u8868", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u4eea\u5668\u89c4\u683c", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u4eea\u5668\u7f16\u53f7", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u4eea\u5668\u540d\u79f0", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u589e", None))
        self.borrowMenu.setTitle(QCoreApplication.translate("MainWindow", u"\u501f\u7528\u7ba1\u7406", None))
        self.recordMenu.setTitle(QCoreApplication.translate("MainWindow", u"\u8bb0\u5f55\u67e5\u8be2", None))
        self.userMenu.setTitle(QCoreApplication.translate("MainWindow", u"\u4eba\u5458\u5f55\u5165", None))
        self.productMenu.setTitle(QCoreApplication.translate("MainWindow", u"\u4eea\u5668\u67e5\u8be2", None))
    # retranslateUi

